/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "jpeg.h"

bool_t
xdr_img_t (XDR *xdrs, img_t *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->data, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
